name: MSFlow-BoTorch
channels:
  - defaults
dependencies:
  - botorch
  - numpy
  - pandas
  - python=3.10
  - scikit-learn
  - pip
  - pip:
      - -e /Users/jakobzeitler/Library/Mobile Documents/com~apple~CloudDocs/CausalMinds/Projects/MHSapi/MHSapi/